// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>—ценарий3</b><br>
 * Generated     : <b>2019/04/15 23:13:56</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 10 amd64 10.0 <br>
 * 
 * @since  апрел€ 15, 2019
 * @author Dudoserg
 */
public abstract class —ценарий3Helper extends RationalTestScript
{
	/**
	 * GlassWndClassGlassWindowClass3: with default state.
	 *		.text : null
	 * 		.class : GlassWndClass-GlassWindowClass-3
	 * 		.processName : java.exe
	 * 		.name : null
	 */
	protected TopLevelSubitemTestObject glassWndClassGlassWindowClass3() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("glassWndClassGlassWindowClass3"));
	}
	/**
	 * GlassWndClassGlassWindowClass3: with specific test context and state.
	 *		.text : null
	 * 		.class : GlassWndClass-GlassWindowClass-3
	 * 		.processName : java.exe
	 * 		.name : null
	 */
	protected TopLevelSubitemTestObject glassWndClassGlassWindowClass3(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("glassWndClassGlassWindowClass3"), anchor, flags);
	}
	
	/**
	 * –екламноејгентство: with default state.
	 *		.text : –екламное агентство
	 * 		.class : GlassWndClass-GlassWindowClass-2
	 * 		.processName : java.exe
	 * 		.name : –екламное агентство
	 */
	protected TopLevelSubitemTestObject рекламноејгентствоwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("рекламноејгентствоwindow"));
	}
	/**
	 * –екламноејгентство: with specific test context and state.
	 *		.text : –екламное агентство
	 * 		.class : GlassWndClass-GlassWindowClass-2
	 * 		.processName : java.exe
	 * 		.name : –екламное агентство
	 */
	protected TopLevelSubitemTestObject рекламноејгентствоwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("рекламноејгентствоwindow"), anchor, flags);
	}
	
	

	protected —ценарий3Helper()
	{
		setScriptName("—ценарий3");
	}
	
}

